
export const DOCUMENT_TYPES: string[] = [
  'Bản ghi nhớ',
  'Bản thỏa thuận',
  'Báo cáo',
  'Biên bản',
  'Chỉ thị',
  'Chương trình',
  'Công điện',
  'Công văn',
  'Đề án',
  'Dự án',
  'Giấy giới thiệu',
  'Giấy mời',
  'Giấy nghỉ phép',
  'Giấy ủy quyền',
  'Hợp đồng',
  'Hướng dẫn',
  'Kế hoạch',
  'Nghị quyết (cá biệt)',
  'Phiếu báo',
  'Phiếu chuyển',
  'Phiếu gửi',
  'Phương án',
  'Quy chế',
  'Quy định',
  'Quyết định (cá biệt)',
  'Thông báo',
  'Thông cáo',
  'Thư công',
  'Tờ trình',
];
